# Generated by Django 6.0.2 on 2026-02-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcategory_size_type'),
        ('users', '0003_basket'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='basket',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('user', 'product', 'size')},
        ),
    ]
