# Generated by Django 6.0.2 on 2026-02-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_size_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='size_type',
            field=models.CharField(blank=True, choices=[(None, 'Без размера (Канцелярия)'), ('clothing', 'Одежда (XS, S, M, L, XL)'), ('shoes', 'Обувь (36-45)')], max_length=20, null=True),
        ),
    ]
